from maingame.views.views import *
from maingame.views.views_submit import *
from maingame.views.views_dominion_controls import *
from maingame.views.views_dwarf import *
from maingame.views.views_goblin import *
from maingame.views.views_blessed_order import *
from maingame.views.views_sludgeling import *
from maingame.views.views_biclops import *
from maingame.views.views_mechadragon import *
from maingame.views.views_aethertide_corsairs import *