# Generated by Django 5.1.1 on 2024-09-16 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('resource_produced', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('amount_produced', models.IntegerField(default=0)),
                ('trade_multiplier', models.IntegerField(default=0)),
                ('defense_multiplier', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Deity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('gold', models.IntegerField(default=0)),
                ('ore', models.IntegerField(default=0)),
                ('food', models.IntegerField(default=0)),
                ('lumber', models.IntegerField(default=0)),
                ('gems', models.IntegerField(default=0)),
                ('mana', models.IntegerField(default=0)),
                ('associated_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('housing', models.IntegerField(default=10)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maingame.buildingtype')),
                ('ruler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maingame.player')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ticks_ruled', models.IntegerField(default=0)),
                ('deity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maingame.deity')),
                ('ruler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maingame.player')),
                ('primary_terrain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions_as_primary_terrain', to='maingame.terrain')),
                ('secondary_terrain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions_as_secondary_terrain', to='maingame.terrain')),
            ],
        ),
        migrations.AddField(
            model_name='buildingtype',
            name='ideal_terrain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maingame.terrain'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('dp', models.IntegerField(default=0)),
                ('op', models.IntegerField(default=0)),
                ('gold_cost', models.IntegerField(default=0)),
                ('ore_cost', models.IntegerField(default=0)),
                ('lumber_cost', models.IntegerField(default=0)),
                ('gem_cost', models.IntegerField(default=0)),
                ('mana_cost', models.IntegerField(default=0)),
                ('food_cost', models.IntegerField(default=0)),
                ('sacred_site_requirement', models.IntegerField(default=0)),
                ('associated_deity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maingame.deity')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='starter_units',
            field=models.ManyToManyField(to='maingame.unit'),
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_terrain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maingame.terrain')),
                ('starter_units', models.ManyToManyField(to='maingame.unit')),
            ],
        ),
    ]
