# Generated by Django 5.1.1 on 2025-04-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='description_paragraphs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
