# Generated by Django 5.1.1 on 2025-05-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0002_faction_description_paragraphs'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='last_tick_finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
