# Generated by Django 5.1.1 on 2025-06-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0003_round_last_tick_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='sludgene',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dominion',
            name='name',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
