# Generated by Django 5.1.1 on 2024-09-17 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0003_alter_unit_associated_deity'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='maingame.region'),
            preserve_default=False,
        ),
    ]
