# Generated by Django 5.1.1 on 2024-09-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0004_building_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='housing',
        ),
        migrations.AddField(
            model_name='buildingtype',
            name='housing',
            field=models.IntegerField(default=10),
        ),
    ]
