# Generated by Django 5.1.1 on 2025-07-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0005_dominion_is_protection_ticking'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='extra_text',
            field=models.CharField(default='', max_length=150),
        ),
    ]
