# Generated by Django 5.1.1 on 2024-09-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0006_alter_deity_options_alter_terrain_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
