# Generated by Django 5.1.1 on 2025-07-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0006_event_extra_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='play_if_you',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
