# Generated by Django 5.1.1 on 2025-08-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0007_faction_play_if_you'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominion',
            name='last_tick_played',
            field=models.IntegerField(default=0),
        ),
    ]
