# Generated by Django 5.1.1 on 2024-09-17 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0007_faction_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='faction',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='maingame.faction'),
            preserve_default=False,
        ),
    ]
