# Generated by Django 5.1.1 on 2025-09-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0008_dominion_last_tick_played'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dominion',
            name='score',
        ),
        migrations.AddField(
            model_name='dominion',
            name='score_list',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
