# Generated by Django 5.1.1 on 2024-09-17 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0008_player_faction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='faction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='maingame.faction'),
        ),
    ]
