# Generated by Django 5.1.1 on 2024-09-17 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0009_alter_player_faction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='name',
        ),
        migrations.AlterField(
            model_name='building',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buildings_here', to='maingame.region'),
        ),
    ]
