# Generated by Django 5.1.1 on 2024-09-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0010_remove_building_name_alter_building_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='built_on_ideal_terrain',
            field=models.BooleanField(default=False),
        ),
    ]
