# Generated by Django 5.1.1 on 2024-09-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0011_building_built_on_ideal_terrain'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='perk_string',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='quantity_marshaled',
            field=models.IntegerField(default=0),
        ),
    ]
