# Generated by Django 5.1.1 on 2024-09-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0013_terrain_unit_op_dp_ratio_terrain_unit_perk_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrain',
            name='emoji',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
