# Generated by Django 5.1.1 on 2024-09-18 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0014_terrain_emoji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faction',
            name='preferred_terrain',
        ),
    ]
