# Generated by Django 5.1.1 on 2024-09-18 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0015_remove_faction_preferred_terrain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faction',
            name='starter_units',
        ),
        migrations.RemoveField(
            model_name='player',
            name='units_available',
        ),
        migrations.AddField(
            model_name='unit',
            name='faction_for_which_is_default',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='maingame.faction'),
        ),
        migrations.AddField(
            model_name='unit',
            name='is_trainable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='ruler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='maingame.player'),
        ),
        migrations.AlterField(
            model_name='building',
            name='ruler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='maingame.player'),
        ),
        migrations.AlterField(
            model_name='region',
            name='ruler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='maingame.player'),
        ),
    ]
