# Generated by Django 5.1.1 on 2024-09-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0016_remove_faction_starter_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingtype',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
