# Generated by Django 5.1.1 on 2024-09-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0017_alter_buildingtype_name_alter_unit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingtype',
            name='resource_produced',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
