# Generated by Django 5.1.1 on 2024-09-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0018_alter_buildingtype_resource_produced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='quantity_in_region_id',
        ),
        migrations.AddField(
            model_name='region',
            name='units_here_dict',
            field=models.JSONField(default=dict),
        ),
    ]
