# Generated by Django 5.1.1 on 2024-09-19 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0020_alter_unit_associated_deity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('ticks_to_arrive', models.IntegerField(default=12)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journey_destination_set', to='maingame.region')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journey_origin_set', to='maingame.region')),
                ('ruler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maingame.player')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maingame.unit')),
            ],
        ),
    ]
