# Generated by Django 5.1.1 on 2024-09-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0021_journey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='origin',
        ),
    ]
