# Generated by Django 5.1.1 on 2024-09-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0022_remove_journey_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='deity',
            name='emoji',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
