# Generated by Django 5.1.1 on 2024-09-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0023_deity_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='resources_dict',
            field=models.JSONField(default=dict),
        ),
    ]
