# Generated by Django 5.1.1 on 2024-09-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0024_player_resources_dict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='resources_dict',
            new_name='resource_dict',
        ),
        migrations.RemoveField(
            model_name='deity',
            name='emoji',
        ),
        migrations.RemoveField(
            model_name='player',
            name='food',
        ),
        migrations.RemoveField(
            model_name='player',
            name='gems',
        ),
        migrations.RemoveField(
            model_name='player',
            name='gold',
        ),
        migrations.RemoveField(
            model_name='player',
            name='lumber',
        ),
        migrations.RemoveField(
            model_name='player',
            name='mana',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ore',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='food_cost',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='gem_cost',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='gold_cost',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='lumber_cost',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='mana_cost',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='ore_cost',
        ),
        migrations.AddField(
            model_name='unit',
            name='cost_dict',
            field=models.JSONField(default=dict),
        ),
    ]
