# Generated by Django 5.1.1 on 2024-09-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0025_rename_resources_dict_player_resource_dict_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_starving',
            field=models.BooleanField(default=False),
        ),
    ]
