# Generated by Django 5.1.1 on 2024-09-20 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0028_alter_player_building_types_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='building_types_available',
        ),
        migrations.RemoveField(
            model_name='player',
            name='faction',
        ),
        migrations.AddField(
            model_name='buildingtype',
            name='ruler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='maingame.player'),
        ),
    ]
