# Generated by Django 5.1.1 on 2024-09-20 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0029_remove_player_building_types_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingtype',
            name='ruler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maingame.player'),
        ),
    ]
