# Generated by Django 5.1.1 on 2024-09-20 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0030_alter_buildingtype_ruler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='ruler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maingame.player'),
        ),
        migrations.AlterField(
            model_name='region',
            name='ruler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maingame.player'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='ruler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maingame.player'),
        ),
    ]
