# Generated by Django 5.1.1 on 2024-09-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0031_alter_building_ruler_alter_region_ruler_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_started', models.BooleanField(default=False)),
            ],
        ),
    ]
