# Generated by Django 5.1.1 on 2024-09-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0032_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingtype',
            name='upgrades',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faction',
            name='base_research_cost',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='faction',
            name='base_research_exponent',
            field=models.FloatField(blank=True, default=1.02, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='cost_upgrade_dict',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='unit',
            name='dp_upgrades',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='op_upgrades',
            field=models.IntegerField(default=0),
        ),
    ]
