# Generated by Django 5.1.1 on 2024-09-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0033_buildingtype_upgrades_faction_base_research_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='research_cost',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='player',
            name='research_exponent',
            field=models.FloatField(blank=True, default=1.02, null=True),
        ),
    ]
