# Generated by Django 5.1.1 on 2024-09-20 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0034_player_research_cost_player_research_exponent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingtype',
            name='housing',
        ),
    ]
