# Generated by Django 5.1.1 on 2024-09-20 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0035_remove_buildingtype_housing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faction',
            old_name='base_research_cost',
            new_name='base_upgrade_cost',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='research_cost',
            new_name='upgrade_cost',
        ),
    ]
