# Generated by Django 5.1.1 on 2024-09-20 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0036_rename_base_research_cost_faction_base_upgrade_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faction',
            old_name='base_research_exponent',
            new_name='base_upgrade_exponent',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='research_exponent',
            new_name='upgrade_exponent',
        ),
    ]
