# Generated by Django 5.1.1 on 2024-09-22 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0038_round_delete_rule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='winnder',
            new_name='winner',
        ),
    ]
