# Generated by Django 5.1.1 on 2024-09-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0039_rename_winnder_round_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='units_here_dict',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='has_started',
            field=models.BooleanField(default=True),
        ),
    ]
