# Generated by Django 5.1.1 on 2024-09-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0041_player_protection_ticks_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='invasion_this_tick',
            field=models.BooleanField(default=False),
        ),
    ]
