# Generated by Django 5.1.1 on 2024-09-26 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0042_region_invasion_this_tick'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reference_id', models.IntegerField(default=0)),
                ('reference_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_involved_dict', models.JSONField(blank=True, default=dict, null=True)),
                ('casualties_dict', models.JSONField(blank=True, default=dict, null=True)),
                ('attackers', models.ManyToManyField(to='maingame.player')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maingame.region')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='battles_won', to='maingame.player')),
            ],
        ),
    ]
