# Generated by Django 5.1.1 on 2024-09-26 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0043_event_battle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='battles_won', to='maingame.player'),
        ),
    ]
