# Generated by Django 5.1.1 on 2024-09-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0044_alter_battle_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
