# Generated by Django 5.1.1 on 2024-09-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0046_battle_original_ruler'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='icon',
            field=models.CharField(default='?', max_length=50),
        ),
    ]
