# Generated by Django 5.1.1 on 2024-09-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0047_event_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='dp',
            field=models.IntegerField(default=0),
        ),
    ]
