# Generated by Django 5.1.1 on 2024-09-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0048_battle_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='extra_text',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
