# Generated by Django 5.1.1 on 2024-09-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0049_event_extra_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='extra_text',
            field=models.CharField(default='', max_length=150),
        ),
    ]
