# Generated by Django 5.1.1 on 2024-09-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0050_alter_event_extra_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='has_unread_events',
            field=models.BooleanField(default=False),
        ),
    ]
