# Generated by Django 5.1.1 on 2024-09-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0051_player_has_unread_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notified_players',
            field=models.ManyToManyField(to='maingame.player'),
        ),
    ]
