# Generated by Django 5.1.1 on 2024-09-27 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0052_event_notified_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='associated_deity',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='cost_upgrade_dict',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='dp_upgrades',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='op_upgrades',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='sacred_site_requirement',
        ),
    ]
