# Generated by Django 5.1.1 on 2024-09-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0053_remove_unit_associated_deity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deity',
            name='emoji',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
