# Generated by Django 5.1.1 on 2024-09-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0054_deity_emoji'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deity',
            old_name='emoji',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='terrain',
            old_name='emoji',
            new_name='icon',
        ),
    ]
