# Generated by Django 5.1.1 on 2024-09-27 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0055_rename_emoji_deity_icon_rename_emoji_terrain_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='cost_dict',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='unit',
            name='faction_for_which_is_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maingame.faction'),
        ),
    ]
