# Generated by Django 5.1.1 on 2024-09-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0056_alter_unit_cost_dict_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='perk_string',
        ),
        migrations.AddField(
            model_name='unit',
            name='perk_dict',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
