# Generated by Django 5.1.1 on 2024-09-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0057_remove_unit_perk_string_unit_perk_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='is_starter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_starter_unit',
            field=models.BooleanField(default=False),
        ),
    ]
