# Generated by Django 5.1.1 on 2024-09-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0058_building_is_starter_player_is_starter_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_starter_unit',
        ),
        migrations.AddField(
            model_name='unit',
            name='is_starter',
            field=models.BooleanField(default=False),
        ),
    ]
