# Generated by Django 5.1.1 on 2024-09-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0059_remove_player_is_starter_unit_unit_is_starter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='faction_for_which_is_default',
        ),
        migrations.DeleteModel(
            name='Faction',
        ),
    ]
