# Generated by Django 5.1.1 on 2024-09-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0060_remove_unit_faction_for_which_is_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='is_starter',
        ),
        migrations.AddField(
            model_name='buildingtype',
            name='is_starter',
            field=models.BooleanField(default=False),
        ),
    ]
