# Generated by Django 5.1.1 on 2024-09-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0061_remove_building_is_starter_buildingtype_is_starter'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='xp_dict',
            field=models.JSONField(default=dict),
        ),
    ]
