# Generated by Django 5.1.1 on 2024-09-30 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0062_player_xp_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='trade_price_dict',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
