# Generated by Django 5.1.1 on 2024-09-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0063_round_trade_price_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='recent_trades_dict',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
