# Generated by Django 5.1.1 on 2024-09-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0065_rename_recent_trades_dict_round_trade_balance_dict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='xp_dict',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
