# Generated by Django 5.1.1 on 2024-10-02 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0067_round_base_trade_price_dict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='trade_balance_dict',
            new_name='resource_bank_dict',
        ),
    ]
