# Generated by Django 5.1.1 on 2024-10-02 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0068_rename_trade_balance_dict_round_resource_bank_dict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='base_trade_price_dict',
        ),
    ]
