# Generated by Django 5.1.1 on 2024-10-02 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0069_remove_round_base_trade_price_dict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='deity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maingame.deity'),
        ),
    ]
