# Generated by Django 5.1.1 on 2024-10-07 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0070_alter_region_deity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='type',
        ),
        migrations.RemoveField(
            model_name='region',
            name='deity',
        ),
        migrations.RemoveField(
            model_name='region',
            name='primary_terrain',
        ),
        migrations.RemoveField(
            model_name='region',
            name='ruler',
        ),
        migrations.RemoveField(
            model_name='region',
            name='secondary_terrain',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='target',
        ),
        migrations.RemoveField(
            model_name='building',
            name='region',
        ),
        migrations.RemoveField(
            model_name='building',
            name='built_on_ideal_terrain',
        ),
        migrations.RemoveField(
            model_name='deity',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='player',
            name='resource_dict',
        ),
        migrations.RemoveField(
            model_name='player',
            name='xp_dict',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='quantity_marshaled',
        ),
        migrations.AddField(
            model_name='building',
            name='amount_produced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='acres',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='unit',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_resource_name', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_resource_per_acre', models.IntegerField(default=0)),
                ('ruler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maingame.player')),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maingame.faction'),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('ruler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maingame.player')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='resource_produced',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maingame.resource'),
        ),
        migrations.DeleteModel(
            name='BuildingType',
        ),
        migrations.DeleteModel(
            name='Terrain',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
