# Generated by Django 5.1.1 on 2024-10-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0071_remove_building_type_remove_region_deity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='starting_buildings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
