# Generated by Django 5.1.1 on 2024-10-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0072_faction_starting_buildings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='resource_produced',
        ),
        migrations.AddField(
            model_name='building',
            name='defense_multiplier',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='is_starter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='resource_produced_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='trade_multiplier',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='upgrades',
            field=models.IntegerField(default=0),
        ),
    ]
