# Generated by Django 5.1.1 on 2024-10-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0073_remove_building_resource_produced_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
