# Generated by Django 5.1.1 on 2024-10-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0074_alter_resource_icon_alter_resource_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='construction_dict',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
