# Generated by Django 5.1.1 on 2024-10-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0075_building_construction_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='is_buildable',
            field=models.BooleanField(default=True),
        ),
    ]
