# Generated by Django 5.1.1 on 2024-10-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0076_building_is_buildable'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='building_primary_resource_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='faction',
            name='building_secondary_resource_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='building_primary_cost_per_acre',
            field=models.IntegerField(default=100),
        ),
    ]
