# Generated by Django 5.1.1 on 2024-10-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0077_faction_building_primary_resource_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faction',
            name='building_primary_resource_name',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='building_secondary_resource_name',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='primary_resource_name',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='primary_resource_per_acre',
        ),
        migrations.AddField(
            model_name='player',
            name='building_primary_resource_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='building_secondary_resource_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='primary_resource_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='primary_resource_per_acre',
            field=models.IntegerField(default=100),
        ),
    ]
