# Generated by Django 5.1.1 on 2024-10-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0079_faction_building_primary_resource_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faction',
            name='ruler',
        ),
        migrations.AddField(
            model_name='faction',
            name='building_primary_cost_per_acre',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='faction',
            name='building_secondary_cost_per_acre',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='player',
            name='building_secondary_cost_per_acre',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='primary_resource_per_acre',
            field=models.IntegerField(default=0),
        ),
    ]
