# Generated by Django 5.1.1 on 2024-10-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0080_remove_faction_ruler_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='building_primary_cost_per_acre',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='faction',
            name='building_secondary_cost_per_acre',
            field=models.IntegerField(default=1),
        ),
    ]
