# Generated by Django 5.1.1 on 2024-10-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0081_alter_faction_building_primary_cost_per_acre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='training_dict',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='player',
            name='upgrade_cost',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='player',
            name='upgrade_exponent',
            field=models.FloatField(blank=True, default=1.03, null=True),
        ),
    ]
