# Generated by Django 5.1.1 on 2024-10-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0083_player_complacency'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='returning_dict',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
