# Generated by Django 5.1.1 on 2024-10-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0084_unit_returning_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='base_price_dict',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
