# Generated by Django 5.1.1 on 2024-10-10 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0088_remove_battle_attackers_remove_battle_original_ruler_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='extra_text',
            new_name='message_override',
        ),
    ]
