# Generated by Django 5.1.1 on 2024-10-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0089_rename_extra_text_event_message_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='perk_dict',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
