# Generated by Django 5.1.1 on 2024-10-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0090_player_perk_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='faction_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
