# Generated by Django 5.1.1 on 2024-10-11 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0091_player_faction_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='is_starter',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='is_starter',
        ),
    ]
