# Generated by Django 5.1.1 on 2024-10-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0092_remove_building_is_starter_remove_unit_is_starter'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='available_research',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
