# Generated by Django 5.1.1 on 2024-10-12 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0094_discovery_delete_journey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='available_research',
            new_name='available_discoveries',
        ),
    ]
