# Generated by Django 5.1.1 on 2024-10-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0095_rename_available_research_player_available_discoveries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discovery',
            old_name='Description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='discovery',
            name='requirement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='discovery_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='protection_ticks_remaining',
            field=models.IntegerField(default=72),
        ),
    ]
