# Generated by Django 5.1.1 on 2024-10-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0096_rename_description_discovery_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='has_tick_units',
            field=models.BooleanField(default=False),
        ),
    ]
