# Generated by Django 5.1.1 on 2024-10-13 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0097_player_has_tick_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('requirement', models.CharField(blank=True, max_length=50, null=True)),
                ('mana_cost_per_acre', models.IntegerField(default=99)),
                ('ruler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maingame.player')),
            ],
        ),
    ]
