# Generated by Django 5.1.1 on 2024-10-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0098_spell'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='is_starter',
            field=models.BooleanField(default=False),
        ),
    ]
