# Generated by Django 5.1.1 on 2024-10-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0099_spell_is_starter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='quantity',
        ),
        migrations.AddField(
            model_name='unit',
            name='quantity_at_home',
            field=models.IntegerField(default=0),
        ),
    ]
