# Generated by Django 5.1.1 on 2024-10-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0100_remove_unit_quantity_unit_quantity_at_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='show_tutorials',
            field=models.BooleanField(default=True),
        ),
    ]
