# Generated by Django 5.1.1 on 2024-10-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0101_player_show_tutorials'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='learned_discoveries',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
