# Generated by Django 5.1.1 on 2024-10-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0106_player_last_bought_resource_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
