# Generated by Django 5.1.1 on 2024-10-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0108_player_is_abandoned'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='theme',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
