# Generated by Django 5.1.1 on 2024-10-20 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0109_player_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='dark_mode',
        ),
    ]
