# Generated by Django 5.1.1 on 2024-10-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0110_remove_player_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='ticks_left',
            field=models.IntegerField(default=0),
        ),
    ]
