# Generated by Django 5.1.1 on 2024-10-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0111_round_start_time_round_ticks_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='has_started',
            field=models.BooleanField(default=False),
        ),
    ]
