# Generated by Django 5.1.1 on 2024-10-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0113_player_use_am_pm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='theme',
            field=models.CharField(blank=True, default='ODA', max_length=50, null=True),
        ),
    ]
