# Generated by Django 5.1.1 on 2024-10-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0114_alter_player_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='discovery',
            name='associated_unit_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
