# Generated by Django 5.1.1 on 2024-10-29 01:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0115_discovery_associated_unit_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player',
            new_name='Dominion',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='notified_players',
            new_name='notified_dominions',
        ),
    ]
