# Generated by Django 5.1.1 on 2024-10-29 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0116_rename_player_dominion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dominion',
            name='show_tutorials',
        ),
        migrations.RemoveField(
            model_name='dominion',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='dominion',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='dominion',
            name='use_am_pm',
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('show_tutorials', models.BooleanField(default=True)),
                ('theme', models.CharField(blank=True, default='ODA', max_length=50, null=True)),
                ('use_am_pm', models.BooleanField(default=True)),
                ('associated_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
