# Generated by Django 5.1.1 on 2024-10-30 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0118_usersettings_display_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='icon',
            new_name='category',
        ),
    ]
