# Generated by Django 5.1.1 on 2024-10-30 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0119_rename_icon_event_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='icon',
        ),
    ]
