# Generated by Django 5.1.1 on 2024-10-30 04:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0120_remove_resource_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
