# Generated by Django 5.1.1 on 2024-10-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0121_battle_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='casualties_dict',
        ),
        migrations.AddField(
            model_name='battle',
            name='total_casualties',
            field=models.IntegerField(default=0),
        ),
    ]
