# Generated by Django 5.1.1 on 2024-10-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0122_remove_battle_casualties_dict_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='total_casualties',
        ),
        migrations.AddField(
            model_name='battle',
            name='battle_report_notes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
