# Generated by Django 5.1.1 on 2024-11-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0123_remove_battle_total_casualties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discovery',
            name='not_for_factions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='dominion',
            name='building_secondary_cost_per_acre',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='dominion',
            name='upgrade_cost',
            field=models.IntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(blank=True, default='OpenDominion', max_length=50, null=True),
        ),
    ]
