# Generated by Django 5.1.1 on 2024-11-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0125_alter_dominion_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominion',
            name='failed_defenses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dominion',
            name='sucessful_invasions',
            field=models.IntegerField(default=0),
        ),
    ]
