# Generated by Django 5.1.1 on 2024-11-17 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0126_dominion_failed_defenses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dominion',
            old_name='sucessful_invasions',
            new_name='successful_invasions',
        ),
    ]
