# Generated by Django 5.1.1 on 2024-11-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0127_rename_sucessful_invasions_dominion_successful_invasions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='ticks_left',
        ),
        migrations.AddField(
            model_name='round',
            name='ticks_passed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='round',
            name='ticks_to_end',
            field=models.IntegerField(default=0),
        ),
    ]
