# Generated by Django 5.1.1 on 2024-11-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0131_rename_requirements_discovery_required_discoveries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominion',
            name='determination',
            field=models.IntegerField(default=0),
        ),
    ]
