# Generated by Django 5.1.1 on 2024-11-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0134_alter_dominion_acres'),
    ]

    operations = [
        migrations.AddField(
            model_name='discovery',
            name='required_perk_dict',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='dominion',
            name='upgrade_cost',
            field=models.IntegerField(default=50000),
        ),
        migrations.AlterField(
            model_name='dominion',
            name='upgrade_exponent',
            field=models.FloatField(blank=True, default=1.01, null=True),
        ),
    ]
