# Generated by Django 5.1.1 on 2024-11-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0136_discovery_required_discoveries_or'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='ticks_to_end',
            field=models.IntegerField(default=672),
        ),
    ]
