# Generated by Django 5.1.1 on 2024-11-24 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0138_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='theme_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maingame.theme'),
        ),
    ]
