# Generated by Django 5.1.1 on 2024-11-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0139_usersettings_theme_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
