# Generated by Django 5.1.1 on 2024-11-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0140_theme_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='creator_user_settings_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
