# Generated by Django 5.1.1 on 2024-11-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0141_theme_creator_user_settings_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='input_background',
            field=models.CharField(default='#000000', max_length=50),
        ),
        migrations.AddField(
            model_name='theme',
            name='input_text',
            field=models.CharField(default='#FFFFFF', max_length=50),
        ),
    ]
