# Generated by Django 5.1.1 on 2024-11-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0144_dominion_highest_raw_op_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominion',
            name='highest_raw_op_sent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
