# Generated by Django 5.1.1 on 2024-11-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0144_usersettings_is_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='tutorial_stage',
            field=models.IntegerField(default=0),
        ),
    ]
