# Generated by Django 5.1.1 on 2024-11-26 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0145_alter_dominion_highest_raw_op_sent'),
        ('maingame', '0145_usersettings_tutorial_stage'),
    ]

    operations = [
    ]
