# Generated by Django 5.1.1 on 2024-11-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0146_merge_20241125_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
    ]
