# Generated by Django 5.1.1 on 2024-11-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0147_alter_usersettings_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='juicy_target_threshold',
            field=models.FloatField(default=0.66),
        ),
    ]
