# Generated by Django 5.1.1 on 2024-12-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0148_usersettings_juicy_target_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='juicy_target_threshold',
            field=models.FloatField(default=0),
        ),
    ]
