# Generated by Django 5.1.1 on 2024-12-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0150_building_percent_of_land'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='is_ticking',
            field=models.BooleanField(default=False),
        ),
    ]
