# Generated by Django 5.1.1 on 2024-12-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0151_round_is_ticking'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='cooldown',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spell',
            name='cooldown_remaining',
            field=models.IntegerField(default=0),
        ),
    ]
