# Generated by Django 5.1.1 on 2024-12-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0152_spell_cooldown_spell_cooldown_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='is_targeted',
            field=models.BooleanField(default=False),
        ),
    ]
