# Generated by Django 5.1.1 on 2024-12-31 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0153_spell_is_targeted'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominion',
            name='op_quested',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dominion',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
