# Generated by Django 5.1.1 on 2024-12-31 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0156_battle_stolen_artifact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='stolen_artifact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='maingame.artifact'),
        ),
    ]
