# Generated by Django 5.1.1 on 2025-01-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0157_alter_battle_stolen_artifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='hide_zero_resources',
            field=models.BooleanField(default=False),
        ),
    ]
