# Generated by Django 5.1.1 on 2025-01-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0158_usersettings_hide_zero_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='artifact_roll_string',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
