# Generated by Django 5.1.1 on 2025-02-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0159_battle_artifact_roll_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='is_upgradable',
            field=models.BooleanField(default=True),
        ),
    ]
