# Generated by Django 5.1.1 on 2025-02-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0163_remove_battle_stolen_artifact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechmodule',
            name='attached',
            field=models.BooleanField(default=False),
        ),
    ]
