# Generated by Django 5.1.1 on 2025-02-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0164_mechmodule_attached'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechmodule',
            name='attached',
        ),
        migrations.AddField(
            model_name='mechmodule',
            name='zone',
            field=models.CharField(choices=[('mech', 'mech'), ('hangar', 'hangar'), ('repair', 'repair')], default='hangar', max_length=50),
        ),
    ]
