# Generated by Django 5.1.1 on 2025-02-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0165_remove_mechmodule_attached_mechmodule_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechmodule',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
