# Generated by Django 5.1.1 on 2025-02-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0166_mechmodule_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='produced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='spent',
            field=models.IntegerField(default=0),
        ),
    ]
