# Generated by Django 5.1.1 on 2025-02-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0167_resource_produced_resource_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='gained',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='lost',
            field=models.IntegerField(default=0),
        ),
    ]
