# Generated by Django 5.1.1 on 2025-02-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0168_unit_gained_unit_lost'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominion',
            name='acres_gained',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dominion',
            name='acres_lost',
            field=models.IntegerField(default=0),
        ),
    ]
