# Generated by Django 5.1.1 on 2025-02-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0169_dominion_acres_gained_dominion_acres_lost'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='bugs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
