# Generated by Django 5.1.1 on 2025-02-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0171_round_has_bugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='discovery',
            name='associated_module_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
