# Generated by Django 5.1.1 on 2025-02-21 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0172_discovery_associated_module_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dominion',
            name='building_primary_cost_per_acre',
        ),
        migrations.RemoveField(
            model_name='dominion',
            name='building_primary_resource_name',
        ),
        migrations.RemoveField(
            model_name='dominion',
            name='building_secondary_cost_per_acre',
        ),
        migrations.RemoveField(
            model_name='dominion',
            name='building_secondary_resource_name',
        ),
        migrations.RemoveField(
            model_name='dominion',
            name='last_bought_resource_name',
        ),
        migrations.RemoveField(
            model_name='dominion',
            name='last_sold_resource_name',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='building_primary_cost_per_acre',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='building_primary_resource_name',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='building_secondary_cost_per_acre',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='building_secondary_resource_name',
        ),
        migrations.CreateModel(
            name='Sludgene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('op', models.IntegerField(default=0)),
                ('dp', models.IntegerField(default=0)),
                ('return_ticks', models.IntegerField(default=12)),
                ('casualty_rate', models.FloatField(default=1)),
                ('resource_produced_name', models.CharField(blank=True, choices=[('food', 'food'), ('ore', 'ore'), ('wood', 'wood'), ('mana', 'mana')], max_length=50, null=True)),
                ('amount_produced', models.FloatField(default=1)),
                ('cost_goop_multiplier', models.FloatField(default=1)),
                ('upkeep_goop_multiplier', models.FloatField(default=1)),
                ('ruler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maingame.dominion')),
            ],
        ),
    ]
