# Generated by Django 5.1.1 on 2025-02-21 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0173_remove_dominion_building_primary_cost_per_acre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sludgene',
            old_name='amount_produced',
            new_name='amount_secreted',
        ),
        migrations.RenameField(
            model_name='sludgene',
            old_name='resource_produced_name',
            new_name='resource_secreted_name',
        ),
    ]
