# Generated by Django 5.1.1 on 2025-02-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0175_remove_sludgene_cost_goop_multiplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sludgene',
            name='cost_type',
            field=models.CharField(blank=True, choices=[('primary', 'primary'), ('secondary', 'secondary'), ('hybrid', 'hybrid')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sludgene',
            name='upkeep_type',
            field=models.CharField(blank=True, choices=[('primary', 'primary'), ('secondary', 'secondary'), ('hybrid', 'hybrid')], max_length=50, null=True),
        ),
    ]
