# Generated by Django 5.1.1 on 2025-02-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0176_sludgene_cost_type_sludgene_upkeep_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sludgene',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
    ]
