# Generated by Django 5.1.1 on 2025-02-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0178_faction_invasion_consequences'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='quantity_in_void',
            field=models.IntegerField(default=0),
        ),
    ]
