# Generated by Django 5.1.1 on 2025-02-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0180_dominion_acres_in_void'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominion',
            name='void_return_cost',
            field=models.IntegerField(default=0),
        ),
    ]
