# Generated by Django 5.1.1 on 2025-03-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0181_dominion_void_return_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechmodule',
            name='battery_current',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mechmodule',
            name='battery_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mechmodule',
            name='upgrade_increases_capacity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mechmodule',
            name='upgrade_increases_durability',
            field=models.BooleanField(default=True),
        ),
    ]
