# Generated by Django 5.1.1 on 2025-03-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0182_mechmodule_battery_current_mechmodule_battery_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechmodule',
            name='is_upgradable',
            field=models.BooleanField(default=True),
        ),
    ]
