# Generated by Django 5.1.1 on 2025-03-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0183_mechmodule_is_upgradable'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominion',
            name='invasion_consequences',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
