# Generated by Django 5.1.1 on 2025-03-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0184_dominion_invasion_consequences'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominion',
            name='times_ruler_killed',
            field=models.IntegerField(default=0),
        ),
    ]
