# Generated by Django 5.1.1 on 2025-03-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0185_dominion_times_ruler_killed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominion',
            name='ruler_respawn_timer',
            field=models.IntegerField(default=0),
        ),
    ]
