# Generated by Django 5.1.1 on 2025-03-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0186_dominion_ruler_respawn_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominion',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
