# Generated by Django 5.1.1 on 2025-03-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0187_dominion_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='description',
            # field=models.JSONField(blank=True, default=list),
            field=models.CharField(blank=True, default='Placeholder description', max_length=1000, null=True),
        ),
    ]
