# Generated by Django 5.1.1 on 2025-03-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0188_alter_faction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='description_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='faction',
            name='description',
            field=models.CharField(blank=True, default='Placeholder description', max_length=1000, null=True),
        ),
    ]
