# Generated by Django 5.1.1 on 2025-03-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0189_faction_description_list_alter_faction_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faction',
            name='description_list',
        ),
    ]
