# Generated by Django 5.1.1 on 2025-03-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0190_remove_faction_description_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='description_list',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
