# Generated by Django 5.1.1 on 2025-04-04 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0192_faction_description_paragraphs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faction',
            name='description_paragraphs',
        ),
    ]
